trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '17'
      architecture: 'x64'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  # Optional: Push changes back to repo
  - script: |
      git config user.email "buildagent@mycompany.com"
      git config user.name "Build Agent"
      git remote set-url origin https://$(System.AccessToken)@dev.azure.com/ORG_NAME/PROJECT/_git/REPO
      git add .
      git commit -m "Automated changes from pipeline"
      git push origin HEAD:main
    env:
      System.AccessToken: $(System.AccessToken)
    displayName: 'Commit & Push changes back to Git'
