trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  # Optional: Push changes back to repo
  - script: |
      echo "##[section]Configuring Git"
      git config --global user.email "buildagent@mycompany.com"
      git config --global user.name "Build Agent"
      
      echo "##[section]Setting remote with token"
      git remote set-url origin https://$(System.AccessToken)@$(Build.Repository.Uri)
      
      echo "##[section]Checking out source branch"
      git checkout -B $(Build.SourceBranchName)
      
      echo "##[section]Committing changes"
      git add .
      git commit -m "Automated changes from pipeline $(Build.BuildId)" || echo "No changes to commit"
      
      echo "##[section]Pushing changes"
      git push origin $(Build.SourceBranchName)
    env:
      System.AccessToken: $(System.AccessToken)
    displayName: 'Commit & Push changes back to Git'
