trigger:
  branches:
    include:
      - main   # Trigger pipeline on pushes to main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  DEPLOY_PATH: '/var/www/html'  # Path on your Hostinger server

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        steps:
          # Checkout the GitHub repository
          - checkout: self

          # Copy files to Hostinger server using Azure DevOps SSH service connection
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'Smile-ssh-service-connection'     # Name of your SSH service connection
              sourceFolder: '$(System.DefaultWorkingDirectory)'
              contents: '**/*'
              targetFolder: '$(DEPLOY_PATH)'
              cleanTargetFolder: true          # Optional: clean remote folder before copy

          # Run commands on the remote server
          - task: SSH@0
            inputs:
              sshEndpoint: 'Smile-ssh-service-connection'     # Name of your SSH service connection
              runOptions: 'inline'
              inline: |
                cd $(DEPLOY_PATH)
                ls -la
                
        
                # Example commands, modify as needed
                # npm install
                # pm2 restart app
